Update Head.php
AOEpeople/Aoe_JsCssTstamp pull request #11
Opened 2017-08-18 14:13 UTC by priyanka-saini

Issue:
1. There were some JS error after installing the module.
2. When the Js and Css files are not merged then timestamp was added only to those files which are in skin folder (No timestamp was there for Js and Css files which are in Js or some other folder).

2018-01-29 11:15 UTC, norgeindian commented on app/code/community/Aoe/JsCssTstamp/Block/Head.php
> +        $versionKey = Mage::getModel('aoejscsststamp/package')->getVersionKey();
This function is protected. To make it work, it should be public. 
Please implement this in your pull request.

2018-01-29 11:17 UTC, norgeindian requested changes

2018-01-29 11:17 UTC, norgeindian commented on app/code/community/Aoe/JsCssTstamp/Block/Head.php
> +        $AddTstampToAssetsJs = Mage::getModel('aoejscsststamp/package')->getAddTstampToAssetsJs();
This call does not work. I would recommend to change it to:
$AddTstampToAssetsJs = Mage::getStoreConfig('dev/js/addTstampToJsFiles');

2018-01-29 11:17 UTC, norgeindian commented on app/code/community/Aoe/JsCssTstamp/Block/Head.php
> +        $versionKey = Mage::getModel('aoejscsststamp/package')->getVersionKey();
This function is protected. To make it work, it should be public.
Please implement this in your pull request.

2018-01-31 15:27 UTC, sprankhub commented
Fixed with #12.

2018-01-31 15:27 UTC, closed without merging